subscribed_events = [
    { identifier = "deposit", addresses = ["erd1", "erd1"] }
]

# Possible values: sha256, keccak, blake2b
hasher_type = "blake2b"

[web_socket]
    url = "localhost:22111"
    # Possible values: json, gogo protobuf. Should be compatible with mx-chain-node outport driver config
    marshaller_type = "gogo protobuf"
    # This flag describes the mode to start the WebSocket connector. Can be "client" or "server"
    mode = "client"
    # Retry duration (receive/send data/acknowledge) in seconds
    retry_duration = 5
    # This flag specifies if we should send an acknowledge signal upon receiving data
    with_acknowledge = true
    # Signals if in case of data payload processing error, we should send the ack signal or not. If you want to block
    # incoming data in case of a local error, this should be set to true.
    blocking_ack_on_error = false
    # The duration in seconds to wait for an acknowledgement message
    acknowledge_timeout = 60
