name: Build

on:
  pull_request:
    branches: [ main, feat/* ]
    types: [ opened, ready_for_review ]
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.7
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/server/cmd/server && go build .
          cd ${GITHUB_WORKSPACE}/client/cmd/client && go build .