name: Build

on:
  pull_request:
    branches: [ main, feat/* ]
    types: [ opened, ready_for_review ]
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.6
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/cmd/notifier && go build .
